[package]
name = "intel8080_assembler"
version = "0.1.0"
authors = ["Agustin Chiappe Berrini <jnieve@gmail.com>"]

[lib]
path = "src/lib/mod.rs"

[dependencies]
intel8080cpu = { path = "../intel8080cpu" }
failure = "0.1"