#!/bin/bash

set -euo pipefail

file_path=${1:?First argument should be the file}
file=$(basename "$1")
folder=$(mktemp -d)
trap "rm -fr $folder; exit" EXIT
cargo run "$file_path" "$folder"/"$file".rom
cd ../disassembler
cargo run intel8080 "$folder"/"$file".rom | grep -v NOP > "$folder"/cpudiag.actual.asm
cd ../intel8080_assembler

diff ./tests/"$file".out "$folder"/cpudiag.actual.asm