#!/bin/bash
set -xeuo pipefail

USAGE="create-empty-wavs [game folder]"

folder=${1:?$USAGE}

for i in $(seq 1 9); do
    ffmpeg -ar 48000 -t 5 -f s16le -acodec pcm_s16le -ac 2 -i /dev/zero -acodec copy "$folder"/"$i".wav;
done