[package]
name = "intel8080cpu"
version = "0.1.0"
authors = ["AgustinCB <jnieve@gmail.com>"]

[dependencies]
failure = { version = "0.1.6", features = ["derive"] }
cpu = { path = "../cpu", version="0.1.1" }
